apiVersion: v2
name: cssa
description: Computer Science Student Association web application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - nextjs
  - cssa
  - student-association
maintainers:
  - name: CSSA Team

dependencies:
  - name: postgresql
    version: "16.4.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
