apiVersion: v2
name: tech-club
description: Willamette Technology Club web application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - nextjs
  - tech-club
  - student-association
maintainers:
  - name: Willamette Technology Club Team

dependencies:
  - name: postgresql
    version: "16.4.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
