apiVersion: v2
name: tech-club
description: Student Technology Association web application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - nextjs
  - tech-club
  - student-association
maintainers:
  - name: Tech Club Team

dependencies:
  - name: postgresql
    version: "16.4.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
