{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "tech-club.fullname" . }}-external
  labels:
    {{- include "tech-club.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "tech-club.secretName" . }}
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: tech-club/database
        property: url
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: tech-club/nextauth
        property: secret
    - secretKey: GITHUB_CLIENT_ID
      remoteRef:
        key: tech-club/github
        property: client_id
    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        key: tech-club/github
        property: client_secret
{{- end }}
